services:
  - type: web
    name: loan-prediction-backend
    runtime: python
    # We run from the root now, using the root app.py as the entry point
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11.0
